// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    user: 'root',
    password: '',
    host: 'localhost',
    port: 3306,
    database: 'chanzhi',
    save: 'backup'
  };

}).call(this);
